# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
  
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
staging:
  adapter: sqlite3
  database: db/staging.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  #database: bolao_test
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  #username: bolao
  #password: bolao

production:
  adapter: postgresql
  database: bolao_production
  pool: 5
  timeout: 5000
  username: bolao
  password: bolao
